
# ------------------------------------------------------------
# 1. Request an ACM certificate
# ------------------------------------------------------------
resource "aws_acm_certificate" "this" {

  # Primary domain name (e.g. example.com)
  domain_name               = var.domain_name

  # Additional domains covered by the same certificate
  # (e.g. www.example.com, api.example.com)
  subject_alternative_names = var.subject_alternative_names

  # Use DNS validation (required for auto-renewal, industry standard)
  validation_method         = "DNS"

  # Tags for ownership, environment, cost tracking
  tags = var.tags

  # Ensures zero downtime when certificate is replaced
  # New cert is created before the old one is destroyed
  lifecycle {
    create_before_destroy = true
  }
}


# ------------------------------------------------------------
# 2. Create Route53 DNS records for certificate validation
# ------------------------------------------------------------
resource "aws_route53_record" "validation" {

  # Loop over all domain validation options provided by ACM
  # One DNS record per domain (root + SANs)
  for_each = {
    for dvo in aws_acm_certificate.this.domain_validation_options :
    dvo.domain_name => {

       # DNS record name generated by ACM
      name   = dvo.resource_record_name

       # DNS record value generated by ACM
      record = dvo.resource_record_value

      # DNS record type (usually CNAME)
      type   = dvo.resource_record_type
    }
  }

  # Hosted Zone ID where the validation records will be created
  zone_id = var.zone_id

   # Record name taken directly from ACM
  name    = each.value.name

  # Record type taken directly from ACM
  type    = each.value.type

  # Low TTL for faster validation
  ttl     = 60

   # DNS record value (must be a list for Route53)
  records = [each.value.record]
}


# ------------------------------------------------------------
# 3. Wait for ACM certificate to be validated and issued
# ------------------------------------------------------------
resource "aws_acm_certificate_validation" "this" {

  # ARN of the certificate that must be validated
  certificate_arn         = aws_acm_certificate.this.arn

  # List of fully-qualified DNS names created above
  # This forces Terraform to wait until DNS validation completes
  validation_record_fqdns = [for r in aws_route53_record.validation : r.fqdn]
}
